### ISSUE TITLE
Edit item issue

### ISSUE THREAD

**Issue by ThanChay** [Arcadier/Mogozay-Support#1]
**Edit event trigger is not working on some device**

This error facing only some device. we expected the trigger must fully work on every device and every user account but now some user can't edit/upload

**Item GUID**
fcf32f58-2db4-4400-95b9-9f2bfa93e311

**Seller Account**
myayadanar@lasource.com.mm

![0f6fdcd1-35a5-4032-8cbf-611b34f7beb1](https://user-images.githubusercontent.com/6531873/72585262-c7f76180-391b-11ea-8c72-edaf42825c9d.jpeg)

**Comment by Arcadier** [comment]
This error message will only appear if an item creation sync has failed. It does not appear if an edit has failed because Item Edit and Item Create are 2 separate scripts.

I also notice that this screenshot was taken yesterday. Can you check again today if your edits are not showing up on your CMS.

We have tried editing and creating items on Live and everything seems to be working as intended.

**Comment by Arcadier** [comment]
Hey @ThanChay this issue is being caused by that device having a too slow connection. As mentionned before, if an edit has not been synced to the CMS. Just do the following:

* Go to the item on the item list page
* Toggle the Purchasable toggle to "No".
* Toggle the Purchasable toggle back to "Yes".
* This toggling back and forth will force sync the edits on to the CMS.

![image](https://user-images.githubusercontent.com/6611854/72586566-34c72780-392d-11ea-915a-40efb8eb92a0.png)
